[package]
name = "advent-of-code-day-9"
version = "0.1.0"
authors = ["Thomas Lent <tcl293@gmail.com>"]
edition = "2018"

[lib]
name = "day_9"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "day_9_bench"
harness = false
