[package]
name = "advent-of-code-day-10"
version = "0.1.0"
authors = ["Thomas Lent <tcl293@gmail.com>"]
edition = "2018"

[lib]
name = "day_10"
path = "src/lib.rs"

[dependencies]
regex = "1.1.0"
lazy_static = "1.2.0"
