[package]
name = "advent-of-code-day-11"
version = "0.1.0"
authors = ["Thomas Lent <tcl293@gmail.com>"]
edition = "2018"

[lib]
name = "day_11"
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "bench"
harness = false
